version: '3'

services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx-container
    image: nginx:1.14
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    container_name: ${PROJECT_NAME}-php-container
    build: ./docker/php-fpm
    restart: always
    volumes:
      - ./:/var/www/html

  db:
    image: library/postgres:12-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
#      - $DB_DATA_PATH:/var/lib/postgresql/data #FIXME: doesnt work if folder already exists
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432